// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more
// letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

package main

import "fmt"

func findTheDifference(s string, t string) byte {
	var result byte
	// XOR all characters of s
	for i := 0; i < len(s); i++ {
		result ^= s[i]
	}
	// XOR all characters of t
	for i := 0; i < len(t); i++ {
		result ^= t[i]
	}
	// The result will be the extra character in t
	return result
}
func main() {

	s := "abcc"
	t := "abccc"

	fmt.Println(string(findTheDifference(s, t)))
}
